### ISSUE TITLE
use tf.convert_to_tensor

### ISSUE THREAD

**Issue by Bledson** [pauloamed/NLP-with-NN#1]
https://github.com/pauloamed/NLP-with-NN/blob/239a73ef0fa9c9e7f3b57c83233310fea715fb0c/word2vec/SGNS1T1.py#L221
since tf has gpu support, there may be performance gains using the `np.asarray` similar function `tf.convert_to_tensor`

**Comment by pauloamed** [comment]
thank you kind bledson
